# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz.xci
# IP: The module: 'clk_147MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_147MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_147MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_147MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz.xci
# IP: The module: 'clk_147MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_147MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_147MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jemushatt/Desktop/vga/vga.srcs/sources_1/ip/clk_147MHz/clk_147MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_147MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
